# Generated by Django 4.0.4 on 2022-05-03 06:00

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
